### ISSUE TITLE
I can't connect to the aarch64-build-box anymore.

### ISSUE THREAD

**Issue by Janik-Haag** [nix-community/aarch64-build-box#166]
It worked after my PR got merged and I noticed it stopped a few days ago. I asked some one with access to the box to check the `/etc/passwd` file and my user isn't in it anymore. I guess it stopped working with the merge of #161  which was merged after my pr but has a older commit.

cc @zowoq

**Comment by Janik-Haag** [comment]
Since I already opened this, I might as well mention #163 (in the hope of it getting merged) which updates the readme about ed25519-sk keys and updates mine :see_no_evil:

**Comment by zowoq** [comment]
> It worked after my PR got merged and I noticed it stopped a few days ago. I asked some one with access to the box to check the `/etc/passwd` file and my user isn't in it anymore. I guess it stopped working with the merge of #161 which was merged after my pr but has a older commit.

In https://github.com/nix-community/aarch64-build-box/pull/162#issuecomment-1652738762 I said that the deployment pipeline was offline and it is still offline. I believe that the box hasn't actually been deployed since https://github.com/nix-community/aarch64-build-box/commit/1f76f7c9421553816201c52e33800f641a2507d2.

**Comment by Janik-Haag** [comment]
Hm maybe I have mixed something up then I was sure I was able to connect before. Sorry for the trouble :(

**Comment by cole-h** [comment]
Sorry about the delay. Just got the deployment process fixed, and the box should be available to you now.
