### ISSUE TITLE
experimental Nix feature 'nix-command' is disabled

### ISSUE THREAD

**Issue by timokau** [nix-community/aarch64-build-box#84]
I used to use this command to log into the box when I needed to do something interactive:

```
ssh -t aarch64-nix-community 'nix run nixpkgs.htop nixpkgs.vim nixpkgs.git nixpkgs.tmux nixpkgs.nix-review'
```

This now fails with the error message referenced in the issue title. That's no big deal of course, I can just replace `nix run` with `nix-shell`. But I'm wondering if there's a reason for disabling nix2?

**Comment by lheckemann** [comment]
The reason is that the community box uses nixUnstable; in nixUnstable, the nix command is only allowed when it's enabled through experimental-features. This is done in order to make absolutely clear that the nix command is not a stable feature and that it has no desirable forwards-compatibility properties.

To enable it, you can put it in your nix.conf: `mkdir -p .config/nix && echo experimental-features = nix-command >> .config/nix/nix.conf`. This will be reset when the builder restarts.

**Comment by zowoq** [comment]
nix command and flakes are enabled now: https://github.com/nix-community/aarch64-build-box/commit/fd09d14f32ed84217c1fe32e7da8793e11f7a2d8
